proxy,status,location,real_location,error
http://67.43.227.228:5621,0,America/Toronto,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1c610>: Failed to establish a new connection: [Errno 111] Connection refused')))"
http://98.64.128.182:3128,0,Europe/Amsterdam,Failed,"ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
http://45.144.64.153:8080,0,Europe/Moscow,Failed,"ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
http://135.181.154.225:80,0,Europe/Helsinki,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))"
http://58.243.224.244:8085,0,Asia/Shanghai,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 400 Bad Request')))"
http://47.88.59.79:82,0,America/Los_Angeles,Failed,"ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))"
socks4://177.141.211.254:41469,0,America/Sao_Paulo,Failed,"ConnectionError: SOCKSHTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ed7f4b1ee00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://67.43.228.250:1147,0,America/Toronto,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4d05420>: Failed to establish a new connection: [Errno 111] Connection refused')))"
http://23.247.137.142:80,0,America/Los_Angeles,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4d04610>, 'Connection to 23.247.137.142 timed out. (connect timeout=5)')))"
http://89.145.162.81:3128,0,Europe/Berlin,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1dc30>: Failed to establish a new connection: [Errno 111] Connection refused')))"
http://4.149.210.210:3128,200,America/Los_Angeles,America/Los_Angeles,
http://8.219.97.248:80,0,Asia/Singapore,Failed,"TimeoutError: HTTPSConnectionPool(host='ipinfo.io', port=443): Read timed out. (read timeout=5)"
http://121.224.156.170:8089,0,Asia/Shanghai,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4d05f30>, 'Connection to 121.224.156.170 timed out. (connect timeout=5)')))"
socks4://185.129.250.65:4861,0,Europe/Madrid,Failed,"ConnectionError: SOCKSHTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ed7f4b1cca0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
socks4://27.147.139.225:58080,0,Asia/Dhaka,Failed,"ConnectionError: SOCKSHTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ed7f4b1cac0>, 'Connection to ipinfo.io timed out. (connect timeout=5)'))"
socks4://184.181.217.210:4145,0,America/Chicago,Failed,"ConnectionError: SOCKSHTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))"
http://89.116.23.45:80,0,Europe/Vilnius,Failed,"ProxyError: HTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ProxyError('Unable to connect to proxy', ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ed7f4b1f850>, 'Connection to 89.116.23.45 timed out. (connect timeout=5)')))"
socks4://182.253.122.149:8080,0,Asia/Jakarta,Failed,"ConnectionError: SOCKSHTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ed7f4b1d5d0>, 'Connection to ipinfo.io timed out. (connect timeout=5)'))"
socks4://46.219.1.5:5678,0,Europe/Kiev,Failed,"ConnectionError: SOCKSHTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ed7f4b1f4f0>, 'Connection to ipinfo.io timed out. (connect timeout=5)'))"
socks4://24.24.47.216:8080,0,America/Chicago,Failed,"ConnectionError: SOCKSHTTPSConnectionPool(host='ipinfo.io', port=443): Max retries exceeded with url: /json (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7ed7f4d05150>, 'Connection to ipinfo.io timed out. (connect timeout=5)'))"
